services:
  - type: web
    name: capturar
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: FLASK_ENV
        value: production
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1
